### ISSUE TITLE
Remains many SqlTableDependency's objects

### ISSUE THREAD

**Issue by sepidar902** [christiandelbianco/monitor-table-change-with-sqltabledependency#100]
thanks to SqlTableDependency's authors.
i use SqlTableDependency in my project,first all things are ok,after some days,my app slowed ,when i open my db in sql server management studio ,i see many procedures and message types and ... that was created by SqlTableDependency and not droped them. i think this objects slowes my app,is it correct?
how can i solve it???

**Comment by christiandelbianco** [comment]
Hi,
I guess (but not sure) that this issue can be resolved by version **8.5.2.0** (https://github.com/christiandelbianco/monitor-table-change-with-sqltabledependency/issues/93#issuecomment-418359479).

Currently there is no NuGet Package for this version. 

What i kindly ask you, is to download the source code, compile it and use the DLL in your project.
Then let me know is this error persist or not. In case this bug is fixed with version **8.5.2.0**, i will release a new NuGet package.

Then, regarding old database object created by SqlTableDependency, you can delete all.

**Comment by christiandelbianco** [comment]
Fix released with version **8.5.2.0**.
