### ISSUE TITLE
How to check/re-establish connection? 

### ISSUE THREAD

**Issue by dfkeenan** [christiandelbianco/monitor-table-change-with-sqltabledependency#125]
Hi,

We are using this cool library in one of our websites. (Currently version 7.1.0).  We are using it with SignalR.  We basically copied the example. But we have started having problems where it stops working. The only way we have of fixing the connection at them moment is restarting the App Pool.  

Is there a way to check if the current connection is working and if not Stop/Re-Start the table dependency?

**Comment by dfkeenan** [comment]
I had a bit more of a search in closed issues and found a number of people have asked similar questions. None of which seemed to have a solution.

**Comment by christiandelbianco** [comment]
Sorry for this late response. I have a lot of to do.
When a connection is lost, there is not way to re-connect your SqlTableDependency instance to its database objects (trigger, queue etc...). When the connection is lost, these object are lost too.

In order to see if the SqlTableDependency  is still working you can:
1-check its status. Example: 
if (_tableDependency.Status == TableDependencyStatus.StopDueToError) ...

2-Substribe to OnError event:
this._tableDependency.OnError += this.TableDependency_OnError;

May be you can have a look at test named StatusLostConnectionTest present in GIT HUG
