### ISSUE TITLE
If trigger is deleted SqlTableDependency won't notice

### ISSUE THREAD

**Issue by pmmgit-atl** [christiandelbianco/monitor-table-change-with-sqltabledependency#184]
We are using SqlTableDependency to monitor changes over a set of tables. The stack is ASP.NET core 3.0, ReactJS, REST/Web APIs and SQL Server 2016.
 
We are suspecting either due to SQL timeout or high database CPU, the triggers are being deleted. When this happens, SqlTableDependency won't notice that, so the only way to restore functionality is to issue IISReset so that the triggers are created again. Then it works normally till we have another timeout.

Is there any way SqlTableDependency is able to detect that the objects needed (Triggers, Messaqes, Queues) are missing and recreate them without having to IISReset.

Thanks.

**Comment by christiandelbianco** [comment]
SqlTableDependency's objects are removed when you Dispose() it, or when a crash happend in your application and the connection is close/lost. Expecially in this last case, there is an async and independent thread on SQL Server db that after 3 minutes disposes all SqlTableDependency's objects, in order to leave the DB clean.

For this reason, in not possible ti get notification when SqlTableDependency's objects are deleted.
