### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [christiandelbianco/monitor-table-change-with-sqltabledependency#71]
Good day Sir @christiandelbianco  , I am a graphic designer and I would like to contribute by designing a logo if you will allow me. I think it will give more visibility to your nice project. It will be my gift for free to the project. I am hoping for your positive feedback Sir. :)

Thanks and best regards!
-Tobaloidee

**Comment by Tobaloidee** [comment]
Thanks for the positive feedback Sir, I will start my design now..will post it here asap.. :)

**Comment by Tobaloidee** [comment]
Hi Sir, here's my design concept.. If you have suggestions or modifications in mind please dont hesitate to tell me. :)

![monitor-05](https://user-images.githubusercontent.com/36028424/40632488-356ad2da-631a-11e8-8562-2883d4ba828d.png)

yellow version
icon
![monitor-02](https://user-images.githubusercontent.com/36028424/40632493-3f9af83e-631a-11e8-8608-b0475dfa22aa.png)
logotype
![monitor-04](https://user-images.githubusercontent.com/36028424/40632496-434df4f4-631a-11e8-98f4-572f4bb0b34c.png)

blue version
icon
![monitor-01](https://user-images.githubusercontent.com/36028424/40632504-4ca6f38e-631a-11e8-8aaf-efcf2ca0fc9b.png)
logotype
![monitor-03](https://user-images.githubusercontent.com/36028424/40632508-50c16080-631a-11e8-8b17-59c3af3a31f6.png)

**Comment by christiandelbianco** [comment]
Nice!
I will use the yellow one! At least, the old logo color is the same of the new one 🥇 
By the way, do you have any idea if is possible to include this logo in GIT Repository page?
What i mean is: instead of current BOOK picture you can see on left side of "christiandelbianco/monitor-table-change-with-sqltabledependency", put your logo.

Can you sent me the **logotype** image splitted in two files?

**Comment by christiandelbianco** [comment]
THANKS

**Comment by Tobaloidee** [comment]
Sir, I have uploaded the Logo files & updated the Readme in this PR #73 

you can also download the other variations of the logo in this linked drive of mine

[LOGO FILES](https://drive.google.com/drive/u/0/folders/1-_QgLhL9-2-i0Cp4hqZDxR3q1fGFZRZv)

Thanks so much!! I am so glad that you are accepting my contribution. best regards Sir!

-Tobaloidee

**Comment by christiandelbianco** [comment]
Hi, can you give me your profile home page ? I'd like to add it on Contributors section

**Comment by Tobaloidee** [comment]
JC Abuyot
https://github.com/Tobaloidee

Thanks Sir! Best regards!

**Comment by christiandelbianco** [comment]
Hi Tabaloidee,

I hope you do not offend if i ask you a thing.
The original logo of SqlTableDependency was [this one](http://sqltabledependency.somee.com/).

Also, people that download using Microsoft Visual Studio tool, are used to see this logo:

![2018-05-30 at 17-53-26](https://user-images.githubusercontent.com/13263017/40731895-60b61076-6432-11e8-83e7-50b19356a2e4.png)

So, i want to ask you if you can "improve" the old one, without change it too much, in order to be "back compatible" with the old picture.

Regards

**Comment by Tobaloidee** [comment]
Surely Sir, I will make a new concept and design and will show you again here asap..I saw that logo before i did the design that's why i came up with the yellow color.

**Comment by Tobaloidee** [comment]
here Sir, actually this is my first concept in mind before..

![version 2-01](https://user-images.githubusercontent.com/36028424/40754206-acfaa262-64aa-11e8-9862-54297fdc6ced.png)
![monitor ver 2-02](https://user-images.githubusercontent.com/36028424/40754211-b03b8374-64aa-11e8-9fdd-6319501cf265.png)
