### ISSUE TITLE
Error get HttpContext.Current.Session in TableDependency_OnChanged function

### ISSUE THREAD

**Issue by gromoc** [christiandelbianco/monitor-table-change-with-sqltabledependency#86]
Hi,
I have my platform with users, then I try get Session (HttpContext.Current.Session) but it show NullReferenceExeption (really exist).  Where "int user" is the id of user.
![data](https://user-images.githubusercontent.com/19253724/42719409-a3c6eece-86da-11e8-83ce-728e69cc63ec.PNG)

My goal is delivery the data according the user
My project is MVC

**Comment by christiandelbianco** [comment]
Hi. I thing this the problem is related to SqlTaleDependency change event asynchronicity.

HttpContext.Current is assigned by ASP.NET every time a CLIENT HTTP REQUEST arrives to your IIS.

Events from SqlTableDependency as received in async...not associated to any CLIENT HTTP REQUEST.
In this case you have not HttpContact.Current, because there is no http request context created to serve client request.

Understood?
