### ISSUE TITLE
Retrieve existing records

### ISSUE THREAD

**Issue by amcorch** [christiandelbianco/monitor-table-change-with-sqltabledependency#92]
Is it possible to retrieve records that already exist in the specified database table when the initial connection is created?

**Comment by christiandelbianco** [comment]
No. You must make an initial read by your self. 
Check the application example https://github.com/christiandelbianco/monitor-table-change-with-WPF-WCF-sqltabledependency-example. As soon the WCF client application starts, it reads all records to show the in a GridView. After this initial read, it does not need anymore DB access, because any record change is reported to WCG application that can update the GridView
